FROM bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8

HEALTHCHECK CMD curl -f http://localhost:9870/ || exit 1

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
    build-essential git autoconf automake gdb libffi-dev zlib1g-dev libssl-dev vim \
    && rm -rf /var/lib/apt/lists/*

ENV HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
RUN mkdir -p /hadoop/dfs/name
VOLUME /hadoop/dfs/name

ADD ./hadoop/namenode/run.sh /run.sh
ADD ./hadoop/namenode/init-namenode.sh /init-namenode.sh
RUN chmod a+x /run.sh

EXPOSE 9870

CMD ["/run.sh"]
